package org.iie.po;
// Generated 2014-3-10 13:49:25 by Hibernate Tools 3.2.1.GA



/**
 * LwbCategory generated by hbm2java
 */
public class LwbCategory  implements java.io.Serializable {


     private String id;
     private String fileName;
     private String content;
     private String category;

    public LwbCategory() {
    }

	
    public LwbCategory(String id) {
        this.id = id;
    }
    public LwbCategory(String id, String fileName, String content, String category) {
       this.id = id;
       this.fileName = fileName;
       this.content = content;
       this.category = category;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }




}


