package org.iie.po;
// Generated 2013-12-28 14:50:20 by Hibernate Tools 3.2.1.GA

import com.googlecode.jsonplugin.annotations.JSON;
import java.util.Date;

/**
 * LwbData generated by hbm2java
 */
public class LwbData implements java.io.Serializable {

    private int id;
    private String name;
    private String ip;
    private String url;
    private String resource;
    private Integer clickNum;
    private Date dateTime;
    private String fileName;

    public LwbData() {
    }

    public LwbData(int id) {
        this.id = id;
    }

    public LwbData(int id, String name, String ip, String url, String resource, Integer clickNum, Date dateTime, String fileName) {
        this.id = id;
        this.name = name;
        this.ip = ip;
        this.url = url;
        this.resource = resource;
        this.clickNum = clickNum;
        this.dateTime = dateTime;
        this.fileName = fileName;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getResource() {
        return this.resource;
    }

    public void setResource(String resource) {
        this.resource = resource;
    }

    public Integer getClickNum() {
        return this.clickNum;
    }

    public void setClickNum(Integer clickNum) {
        this.clickNum = clickNum;
    }

    @JSON(format = "yyyy-MM-dd HH:mm:ss")
    public Date getDateTime() {
        return this.dateTime;
    }

    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
}
