package org.iie.po;
// Generated 2014-2-13 12:35:07 by Hibernate Tools 3.2.1.GA

import com.googlecode.jsonplugin.annotations.JSON;
import java.util.Date;

/**
 * LwbSpread generated by hbm2java
 */
public class LwbSpread implements java.io.Serializable {

    private Integer id;
    private String name;
    private String content;
    private Date time;
    private String forward;
    private String status;

    public LwbSpread() {
    }

    public LwbSpread(String status) {
        this.status = status;
    }

    public LwbSpread(String name, String content, Date time, String forward, String status) {
        this.name = name;
        this.content = content;
        this.time = time;
        this.forward = forward;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @JSON(format = "yyyy-MM-dd HH:mm:ss")
    public Date getTime() {
        return this.time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

    public String getForward() {
        return this.forward;
    }

    public void setForward(String forward) {
        this.forward = forward;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
