package org.iie.po;
// Generated 2014-2-10 11:04:41 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * LwbSpecial generated by hbm2java
 */
public class LwbSpecial  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String keyword;
     private char status;
     private Date createTime;

    public LwbSpecial() {
    }

	
    public LwbSpecial(String name, char status, Date createTime) {
        this.name = name;
        this.status = status;
        this.createTime = createTime;
    }
    public LwbSpecial(String name, String keyword, char status, Date createTime) {
       this.name = name;
       this.keyword = keyword;
       this.status = status;
       this.createTime = createTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


