package org.iie.po;
// Generated 2014-2-15 10:08:14 by Hibernate Tools 3.2.1.GA

/**
 * LwbTopic generated by hbm2java
 */
public class LwbTopic implements java.io.Serializable {

    private Long id;
    private String name;

    public LwbTopic() {
    }

    public LwbTopic( Long id) {
        this.id = id;
    }

    public LwbTopic(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
