package org.iie.po;
// Generated 2014-10-11 15:02:10 by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private BigDecimal id;
     private String name;

    public Test() {
    }

	
    public Test(BigDecimal id) {
        this.id = id;
    }
    public Test(BigDecimal id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


